Controllers/ClassesController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Models.Classes;
using SchoolProject.Services.Abstract;

namespace SchoolProject.Controllers;

public class ClassesController : Controller
{
    private readonly IClassService _service;

    public ClassesController(IClassService service)
    {
        _service = service;
    }

    // GET: Classes
    public async Task<IActionResult> Index()
    {
        TempData["ActivePage"] = "3";

        return View(await _service.GetAllAsync());
    }

    // GET: Classes/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound();

        var @class = await _service.GetByIdAsync(id.GetValueOrDefault());

        if (@class == null) return NotFound();

        return View(@class);
    }

    // GET: Classes/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Classes/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Passive")] Class @class)
    {
        if (ModelState.IsValid)
        {
            await _service.AddAsync(@class);

            return RedirectToAction(nameof(Index));
        }

        return View(@class);
    }

    // GET: Classes/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null) return NotFound();

        var @class = await _service.GetByIdAsync(id.GetValueOrDefault());
        if (@class == null) return NotFound();

        return View(@class);
    }

    // POST: Classes/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Passive")] Class @class)
    {
        if (id != @class.Id) return NotFound();

        if (ModelState.IsValid)
        {
            await _service.UpdateAsync(@class);

            return RedirectToAction(nameof(Index));
        }

        return View(@class);
    }

    // GET: Classes/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null) return NotFound();

        var @class = await _service.GetByIdAsync(id.GetValueOrDefault());

        if (@class == null) return NotFound();

        return View(@class);
    }

    // POST: Classes/Delete/5
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var @class = await _service.GetByIdAsync(id);

        if (@class != null) await _service.DeleteAsync(@class);

        return RedirectToAction(nameof(Index));
    }
}

Controllers/ExamsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SchoolProject.Models.Classes;
using SchoolProject.Services.Abstract;

namespace SchoolProject.Controllers;

public class ExamsController : Controller
{
    private readonly ILessonService _lessonService;
    private readonly IExamService _service;

    public ExamsController(IExamService service, ILessonService lessonService)
    {
        _service = service;
        _lessonService = lessonService;
    }

    // GET: Exams
    public async Task<IActionResult> Index()
    {
        TempData["ActivePage"] = "5";

        return View(await _service.GetAllAsync());
    }

    // GET: Exams/Create
    public async Task<IActionResult> Create()
    {
        await SetViewBagData();

        return View();
    }

    // POST: Exams/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,ExamStartDate,ExamEndDate,IsCanceled,LessonId")] Exam exam)
    {
        if (ModelState.IsValid)
        {
            await _service.AddAsync(exam);

            return RedirectToAction(nameof(Index));
        }

        return View(exam);
    }

    private async Task SetViewBagData()
    {
        ViewBag.Lessons = new SelectList(await _lessonService.GetAllAsync(), "Id", "ExamAddDropdownName");
    }

    // GET: Exams/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null) return NotFound();

        var exam = await _service.GetByIdAsync(id.GetValueOrDefault());

        if (exam == null) return NotFound();

        return View(exam);
    }

    // POST: Exams/Delete/5
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var exam = await _service.GetByIdAsync(id);
        if (exam != null) await _service.DeleteAsync(exam);

        return RedirectToAction(nameof(Index));
    }

    // GET: Exams/Cancel/5
    public async Task<IActionResult> Cancel(int? id)
    {
        if (id == null) return NotFound();

        var exam = await _service.GetByIdAsync(id.GetValueOrDefault());
        if (exam == null) return NotFound();

        exam.IsCanceled = true;

        await _service.UpdateAsync(exam);

        return RedirectToAction(nameof(Index));
    }
}

Controllers/LessonsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SchoolProject.Models.Classes;
using SchoolProject.Services.Abstract;

namespace SchoolProject.Controllers;

public class LessonsController : Controller
{
    private readonly IClassService _classService;
    private readonly ILessonService _service;
    private readonly IStudentService _studentService;

    public LessonsController(ILessonService service, IClassService classService, IStudentService studentService)
    {
        _service = service;
        _classService = classService;
        _studentService = studentService;
    }

    // GET: Lessons
    public async Task<IActionResult> Index()
    {
        TempData["ActivePage"] = "4";


        return View(await _service.GetAllAsync());
    }

    // GET: Lessons/Create
    public async Task<IActionResult> Create()
    {
        await SetViewBagData();
        return View();
    }

    // POST: Lessons/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Passive,TeacherId,ClassId")] Lesson lesson)
    {
        if (ModelState.IsValid)
        {
            await _service.AddAsync(lesson);

            return RedirectToAction(nameof(Index));
        }

        return View(lesson);
    }

    // GET: Lessons/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null) return NotFound();

        var lesson = await _service.GetByIdAsync(id.GetValueOrDefault());

        await SetViewBagData();

        if (lesson == null) return NotFound();

        return View(lesson);
    }

    private async Task SetViewBagData()
    {
        ViewBag.Classes = new SelectList(await _classService.GetAllAsync(), "Id", "Name");
        ViewBag.Teachers = new SelectList(await _studentService.GetAllAsync(), "Id", "Name");
    }

    // POST: Lessons/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Passive,ClassId,TeacherId")] Lesson lesson)
    {
        if (id != lesson.Id) return NotFound();

        if (ModelState.IsValid)
        {
            await _service.UpdateAsync(lesson);

            return RedirectToAction(nameof(Index));
        }

        return View(lesson);
    }

    // GET: Lessons/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null) return NotFound();

        var lesson = await _service.GetByIdAsync(id.GetValueOrDefault());

        if (lesson == null) return NotFound();

        return View(lesson);
    }

    // POST: Lessons/Delete/5
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var lesson = await _service.GetByIdAsync(id);

        if (lesson != null) await _service.DeleteAsync(lesson);

        return RedirectToAction(nameof(Index));
    }
}

Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SchoolProject.Models.Classes;
using SchoolProject.Models.Enums;
using SchoolProject.Services.Abstract;

namespace SchoolProject.Controllers;

public class StudentsController : Controller
{
    private readonly IClassService _classService;
    private readonly IStudentService _service;

    public StudentsController(IStudentService service, IClassService classService)
    {
        _service = service;
        _classService = classService;
    }

    // GET: Students
    public async Task<IActionResult> Index()
    {
        TempData["ActivePage"] = "2";

        return View(await _service.GetAllAsync());
    }

    // GET: Students/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound();

        var user = await _service.GetByIdAsync(id.GetValueOrDefault());

        if (user == null) return NotFound();

        return View(user);
    }

    // GET: Students/Create
    public async Task<IActionResult> CreateAsync()
    {
        await SetViewBagData();

        return View();
    }

    // POST: Students/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Surname,Number,Email,ClassId")] User user)
    {
        user.Type = UserType.Tələbə;

        if (ModelState.IsValid)
        {
            await _service.UpdateAsync(user);

            return RedirectToAction(nameof(Index));
        }

        return View(user);
    }

    // GET: Students/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        await SetViewBagData();

        if (id == null) return NotFound();

        var user = await _service.GetByIdAsync(id.GetValueOrDefault());

        if (user == null) return NotFound();

        return View(user);
    }

    private async Task SetViewBagData()
    {
        ViewBag.Classes = new SelectList(await _classService.GetAllAsync(), "Id", "Name");
    }

    // POST: Students/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,ClassId,Name,Surname,Number,Email,Passive")] User user)
    {
        if (id != user.Id) return NotFound();

        user.Type = UserType.Tələbə;

        if (ModelState.IsValid)
        {
            await _service.UpdateAsync(user);

            return RedirectToAction(nameof(Index));
        }

        return View(user);
    }

    // GET: Students/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null) return NotFound();

        var user = await _service.GetByIdAsync(id.GetValueOrDefault());

        if (user == null) return NotFound();

        return View(user);
    }

    // POST: Students/Delete/5
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var user = await _service.GetByIdAsync(id);

        if (user != null) await _service.DeleteAsync(user);

        return RedirectToAction(nameof(Index));
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    @*<title>@ViewData["Title"] - Hamid Musayev's Project</title>*@
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/assets/css/main/app.css">
    <link rel="stylesheet" href="~/assets/css/main/app-dark.css">
    <link rel="shortcut icon" href="~/assets/images/logo/favicon.svg" type="image/x-icon">
    <link rel="shortcut icon" href="~/assets/images/logo/favicon.png" type="image/png">
    <link rel="stylesheet" href="~/assets/css/shared/iconly.css">
</head>
<body>

<div id="sidebar" class="active">
    <div class="sidebar-wrapper active">
        <div class="sidebar-header position-relative">
            <div class="d-flex justify-content-between align-items-center">
                <div class="logo">
                    <a href="index.html">
                        <img src="assets/images/logo/logo.svg" alt="Logo" srcset="">
                    </a>
                </div>
                <div class="theme-toggle d-flex gap-2  align-items-center mt-2">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--system-uicons" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21">
                        <g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M10.5 14.5c2.219 0 4-1.763 4-3.982a4.003 4.003 0 0 0-4-4.018c-2.219 0-4 1.781-4 4c0 2.219 1.781 4 4 4zM4.136 4.136L5.55 5.55m9.9 9.9l1.414 1.414M1.5 10.5h2m14 0h2M4.135 16.863L5.55 15.45m9.899-9.9l1.414-1.415M10.5 19.5v-2m0-14v-2" opacity=".3"></path>
                            <g transform="translate(-210 -1)">
                                <path d="M220.5 2.5v2m6.5.5l-1.5 1.5"></path><circle cx="220.5" cy="11.5" r="4"></circle><path d="m214 5l1.5 1.5m5 14v-2m6.5-.5l-1.5-1.5M214 18l1.5-1.5m-4-5h2m14 0h2"></path>
                            </g>
                        </g>
                    </svg>
                    <div class="form-check form-switch fs-6">
                        <input class="form-check-input  me-0" type="checkbox" id="toggle-dark">
                        <label class="form-check-label"></label>
                    </div>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--mdi" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                        <path fill="currentColor" d="m17.75 4.09l-2.53 1.94l.91 3.06l-2.63-1.81l-2.63 1.81l.91-3.06l-2.53-1.94L12.44 4l1.06-3l1.06 3l3.19.09m3.5 6.91l-1.64 1.25l.59 1.98l-1.7-1.17l-1.7 1.17l.59-1.98L15.75 11l2.06-.05L18.5 9l.69 1.95l2.06.05m-2.28 4.95c.83-.08 1.72 1.1 1.19 1.85c-.32.45-.66.87-1.08 1.27C15.17 23 8.84 23 4.94 19.07c-3.91-3.9-3.91-10.24 0-14.14c.4-.4.82-.76 1.27-1.08c.75-.53 1.93.36 1.85 1.19c-.27 2.86.69 5.83 2.89 8.02a9.96 9.96 0 0 0 8.02 2.89m-1.64 2.02a12.08 12.08 0 0 1-7.8-3.47c-2.17-2.19-3.33-5-3.49-7.82c-2.81 3.14-2.7 7.96.31 10.98c3.02 3.01 7.84 3.12 10.98.31Z"></path>
                    </svg>
                </div>
                <div class="sidebar-toggler  x">
                    <a href="#" class="sidebar-hide d-xl-none d-block">
                        <i class="bi bi-x bi-middle"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="sidebar-menu">
            <ul class="menu">
                <li class="sidebar-title">Menu</li>

                <li class="sidebar-item @(TempData["ActivePage"]?.ToString() == "1" ? "active" : "")">
                    <a asp-controller="Home" asp-action="Index" class="sidebar-link">
                        <i class="bi bi-grid-fill"></i>
                        <span>Əsas səhifə</span>
                    </a>
                </li>

                <li class="sidebar-item @(TempData["ActivePage"]?.ToString() == "2" ? "active" : "")">
                    <a asp-controller="Students" asp-action="Index" class="sidebar-link">
                        <i class="bi bi-people-fill"></i>
                        <span>Tələbələr</span>
                    </a>
                </li>

                <li class="sidebar-item @(TempData["ActivePage"]?.ToString() == "3" ? "active" : "")">
                    <a asp-controller="Classes" asp-action="Index" class="sidebar-link">
                        <i class="bi bi-collection-fill"></i>
                        <span>Siniflər</span>
                    </a>
                </li>

                <li class="sidebar-item @(TempData["ActivePage"]?.ToString() == "4" ? "active" : "")">
                    <a asp-controller="Lessons" asp-action="Index" class="sidebar-link">
                        <i class="bi bi-calendar-fill"></i>
                        <span>Dərslər</span>
                    </a>
                </li>

                <li class="sidebar-item @(TempData["ActivePage"]?.ToString() == "5" ? "active" : "")">
                    <a asp-controller="Exams" asp-action="Index" class="sidebar-link">
                        <i class="bi bi-grid-1x2-fill"></i>
                        <span>İmtahanlar</span>
                    </a>
                </li>

                <li class="sidebar-item  has-sub">
                    <a href="#" class="sidebar-link">
                        <i class="bi bi-person-fill"></i>
                        <span>Hesabım</span>
                    </a>
                    <ul class="submenu ">
                        <li class="submenu-item ">
                            <a href="layout-rtl.html">Redaktə et</a>
                        </li>
                        <li class="submenu-item ">
                            <a href="layout-horizontal.html">Çıxış</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</div>

<main role="main">
    <div id="main">
        @RenderBody()
    </div>
</main>

<script src="~/assets/js/app.js"></script>
<script src="~/assets/js/pages/dashboard.js"></script>

@await RenderSectionAsync("Scripts", false)

</body>
</html>